services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/client/node_modules
      - //./pipe/docker_engine://./pipe/docker_engine
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/project-management
      - JWT_SECRET=Fjd8j3L6k9sQ2pR7vT4xZ8cA1bE5hG0mN3oP6rS9uV2wY5zB7
      - JWT_EXPIRE=30m
      - JWT_REFRESH_EXPIRE=7d
      - DOCKER_SOCKET=//./pipe/docker_engine
    depends_on:
      - mongo
    command: npm run dev-full

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: